# Sistema operativo: Linux
# Distribución: Debian
# Versión: 12
# Fecha: 25 de Septiembre del 2024
# Proyecto: iasd
# Descripción del proyecto: Proyecto iglesia adventista del séptimo día

services:
  git_clone:
    image: alpine/git
    container_name: git_clone_iasd_app
    volumes:
      - /home/juan/Documentos/proyecto_iasd/app:/git
    command: clone https://github.com/carlosjuanco/meca-app.git
    stdin_open: true
    tty: true
    restart: "no"
