# Sistema operativo: Linux
# Distribución: Debian
# Versión: 12
# Fecha: 24 de Septiembre del 2024
# Proyecto: iasd
# Descripción del proyecto: Proyecto iglesia adventista del séptimo día

services:
  git_clone:
    image: alpine/git
    container_name: git_clone_iasd
    volumes:
      - /home/juan/Documentos/proyecto_iasd/api:/git
    command: clone https://github.com/carlosjuanco/zeus-api.git
    stdin_open: true
    tty: true
    restart: "no"
