# Sistema operativo: Linux
# Distribución: Debian
# Versión: 12
# Fecha: 25 de Septiembre del 2024
# Proyecto: iasd
# Descripción del proyecto: Proyecto iglesia adventista del séptimo día

services:
  iasd_app:
    image: node:20.14.0  # La imagen que se va a utilizar
    container_name: iasd_app # Nombre del contenedor
    volumes:
      - /home/juan/Documentos/proyecto_iasd/app:/home/demo # Mapea el volumen de tu directorio local
    ports:
      - "8081:81" # Mapea el puerto 8080 del host al puerto 80 del contenedor
    stdin_open: true  # Equivalente a `-it` para tener un contenedor interactivo
    tty: true # Habilita una terminal interactiva
    command: /bin/bash -c "
      cd home/demo/meca-app && 
      npm install &&
      echo "VUE_APP_BASE_URL=/" > .env && 
      npm run serve -- --port 81 &&
      /bin/bash"  # Ejecuta la secuencia de comandos al iniciar el contenedor
