# Sistema operativo: Windows
# Versión: 11 Home Single Language
# Con: WSL Debian 12.7
# Fecha: 30 de Septiembre del 2024
# Proyecto: iasd
# Descripción del proyecto: Proyecto iglesia adventista del séptimo día

services:
  mysql:
    image: mysql:8.0.34
    container_name: iasd_bd
    environment:
      - MYSQL_ROOT_PASSWORD=juan
      - MYSQL_ROOT_HOST=%
    ports:
      - "3307:3306"
    volumes:
      - /home/juan/Documentos/proyecto_iasd/bd:/var/lib/mysql
      - /home/juan/Documentos/proyecto_iasd/api/zeus-api/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped
